export const menuItemsData = [
  {
    id: 1,
    name: 'Banana',
    info: "From Johnny Depp's fridge",
    price: 1,
    img: '/images/banana.png',
  },
  {
    id: 2,
    name: 'Apple',
    info: "From Margot Robbie's fridge",
    price: 1,
    img: '/images/apple.png',
  },
  {
    id: 3,
    name: 'Bread',
    info: "From Brad Pitt's fridge",
    price: 2,
    img: '/images/bread.png',
  },
  {
    id: 4,
    name: 'Butter',
    info: "From Robert Downey Junior's fridge",
    price: 2,
    img: '/images/butter.png',
  },
  {
    id: 5,
    name: 'Berries',
    info: "From Dwayne Johnson's fridge",
    price: 3,
    img: '/images/berries.png',
  },
  {
    id: 6,
    name: 'Carrots',
    info: "From Timothée Chalamet's fridge",
    price: 4,
    img: '/images/carrots.png',
  },
  {
    id: 7,
    name: 'Cheese',
    info: "From Zendaya's fridge",
    price: 2,
    img: '/images/cheese.png',
  },
  {
    id: 8,
    name: 'Ketchup',
    info: "From Tom Holland's fridge",
    price: 3,
    img: '/images/ketchup.png',
  },
  {
    id: 9,
    name: 'Grapes',
    info: "From Lady Gaga's fridge",
    price: 4,
    img: '/images/grapes.png',
  },
  {
    id: 10,
    name: 'Jam',
    info: "From Al Pacino's fridge",
    price: 7,
    img: '/images/jam.png',
  },
  {
    id: 11,
    name: 'Eggs',
    info: "From Ed Westwick's fridge",
    price: 5,
    img: '/images/eggs.png',
  },
  {
    id: 12,
    name: 'Mayonnaise',
    info: "From Ursula Corbero's fridge",
    price: 3,
    img: '/images/mayo.png',
  },
  {
    id: 13,
    name: 'Meat',
    info: "From Jason Momoa's fridge",
    price: 24,
    img: '/images/meat.png',
  },
  {
    id: 14,
    name: 'Milk',
    info: "From Angelina Jolie's fridge",
    price: 6,
    img: '/images/milk.png',
  },
  {
    id: 15,
    name: 'Pepper',
    info: "From Megan Fox's fridge",
    price: 4,
    img: '/images/pepper.png',
  },
  {
    id: 16,
    name: 'Pickle',
    info: "From Kevin Hart's fridge",
    price: 3,
    img: '/images/pickle.png',
  },
  {
    id: 17,
    name: 'Potatoes',
    info: "From Cardi B's fridge",
    price: 7,
    img: '/images/potatoes.png',
  },
  {
    id: 18,
    name: 'Soft drinks',
    info: "From Ian Somerhalder's fridge",
    price: 12,
    img: '/images/soft drinks.png',
  },
  {
    id: 19,
    name: 'Tomatoes',
    info: "From Charlize Teron's fridge",
    price: 5,
    img: '/images/tomato.png',
  },
  {
    id: 20,
    name: 'Yoghurt',
    info: "From Vin Diesel's fridge",
    price: 7,
    img: '/images/yoghurt.png',
  },
];